### ISSUE TITLE
About the use of fixed training samples

### ISSUE THREAD

**Issue by pangpd** [mhaut/pResNet-HSI#2]
Excuse me, does this program support a fixed number of training samples? For example, the number of training samples is 100, 200, instead of using percentages.

**Comment by mhaut** [comment]
Dear @pangpd 

I've just updated the code (in the commit https://github.com/mhaut/pResNet-HSI/commit/801806836225daa9b2dcc5b605d6f7fd5184c0bf) in order to use a fixed number of training samples. In this sense, if tr_percent < 1, the split will be by percent. Otherwise, if you use tr_percent > 1 then the split will be samples per class. 

Please, let me know if it worked for you.

Best

**Comment by pangpd** [comment]
This is exactly what I need. Thank you very much for your reply. Best wishes to you！
